export default {
    'buy-date':'תאריך קניה',
    'delivery-date':'תאריך מסירה',
    'project':'פרוייקט',
    'bank':'בנק מלווה',
    'contractor':'קבלן',
    'entrepreneur':'יזם',
    'city':'עיר',
    'adress':'כתובת',
    'building':'בניין',
    'floor':'קומה',
    'number':'מספר',
    'rooms':'חדרים',
    'size(sqm)':"גודל(מ''ר)",
    'terrace(sqm)':"מרפסת(מ''ר)",
    'storage':'מחסן',
    'parking':'מחניות',
    'purchase-price':'מחיר קניה',
    'current-value':'שווי נוכחי',
    'loans':'הלוואות',
    'flow':'תזרים',
}